version: "3"

tasks:
  build:
    desc: Build the app
    cmds:
      - GOFLAGS=-mod=mod go build -o bin/gopher-cli main.go

  build-win:
    desc: Build the app
    cmds:
      - GOFLAGS=-mod=mod GOOS=windows GOARCH=amd64 go build -o bin/gopher-cli.exe main.go

  run:
    desc: Run the app
    cmds:
      - GOFLAGS=-mod=mod go run main.go
